import { MigrationInterface, QueryRunner } from 'typeorm'

export class default1671807154895 implements MigrationInterface {
  name = 'default1671807154895'

  public async up (queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`SELECT 
            FILI_COD,
            FILI_UNFE_SIGLA,
            FILI_EMPR_COD,
            FILI_NOME_FANTASIA,
            FILI_CGC,
            FILI_INSC_EST,
            FILI_ENDERECO,
            FILI_TELEFONE,
            FILI_CIDADE,
            FILI_INSC_MUNIC,
            FILI_CEP,
            FILI_CONTATO,
            FILI_BAIRRO,
            FILI_FAX,
            FILI_NOTA_FISCAL_QRP,
            FILI_NUM_PROX_NOTA_FISCAL,
            FILI_NOTA_FISCAL_QRP_SERV,
            FILI_NUM_PROX_NOTA_FISCAL_SERV,
            FILI_NOTA_VENDA_E_SERVICO,
            FILI_NOTA_VENDA_ITENS,
            FILI_NOTA_SERVICO_ITENS,
            FILI_ALMO_COD_PADRAO,
            FILI_CONTRIBUINTE_IPI,
            FILI_DUPLICATA_QRP,
            FILI_LOGOTIPO,
            FILI_NOTA_VENDA_COL,
            FILI_NOTA_SERVICO_COL,
            FILI_PEDIDO_QRP,
            FILI_ORCAMENTO_QRP,
            FILI_CIDA_COD,
            FILI_BAIR_COD,
            FILI_FATURA_QRP,
            FILI_ALIQ_ISS,
            FILI_QTDE_LINHAS_OBS_NF,
            FILI_NUM_PROX_D1,
            FILI_NUM_PROX_NOTA_FISCAL_FAT,
            FILI_EMAIL,
            FILI_SERIE_NF_PRODUTO,
            FILI_SERIE_NF_SERVICO,
            FILI_REGIME_PAGAMENTO_ICMS,
            FILI_TIDS_COD,
            FILI_SITUACAO_NOTA,
            FILI_SERIE_D1,
            FILI_TRANSF_ALMOX_QRP,
            FILI_NOTA_FISCAL_QRP_LOCA,
            FILI_NUM_PROX_NOTA_FISCAL_LOCA,
            FILI_NOTA_LOCACAO,
            FILI_NOTA_LOCA_COL,
            FILI_SERIE_NF_LOCACAO,
            FILI_NOTA_VENDA_E_LOCACAO,
            FILI_COTACAO_LOCACAO_QRP,
            FILI_REPARO_LOCACAO_QRP,
            FILI_NFE_IDLOTE,
            FILI_NFE_PROD,
            FILI_CGA,
            FILI_NUM_PROX_RPS,
            FILI_NFE_SERV,
            FILI_TRANSF_FILIAL_QRP,
            FILI_CONTROLA_CM,
            FILI_PERCENT_CM,
            FILI_INCENTIVADOR_CULTURAL,
            FILI_PERFIL_SPED,
            FILI_GERA_SPED_ICMS
            FILI_GERA_SPED_PIS,
            FILI_TRANF_ALMOX_QRP_SAIDA,
            FILI_CODIGO_EXTRA,
            FILI_CPF_CONTATO,
            FILI_NUMERO_END,
            FILI_NAO_ICMS_ST_RETENC,
            FILI_IND_BLOQ,
            FILI_NOME_CONTADOR,
            FILI_CPF_CONTADOR,
            FILI_CRC_CONTADOR,
            FILI_UNFE_SIGLA_CONTADOR,
            FILI_FONE_CONTADOR,
            FILI_LOGRADOURO_CONTADOR,
            FILI_NUMERO_CONTADOR,
            FILI_BAIRRO_CONTADOR,
            FILI_CEP_CONTADOR,
            FILI_UNFE_SIGLA_DESC_CONTADOR,
            FILI_MUNICIPIO_CONTADOR,
            FILI_EMAIL_CONTADOR,
            FILI_COD_MUNICIPIO_CONTADOR,
            FILI_CGC_CONTADOR,
            FILI_PEDIDO_SERV_QRP,
            FILI_MOVIMENTACOES_QRP,
            FILI_PEDIDO_PROD_QRP,
            FILI_PREST_SERV_OBRA,
            FILI_IMP_TOTAL_VENDA,
            FILI_BOLETIM_LOCACAO_QRP,
            FILI_BOLETIM_LOC_AGRUPADO_QRP,
            FILI_CPF
        FROM
            FILIAL`)
  }

  public async down (queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "filial"')
  }
}
